name: geneprofanalysis

channels:
  - anaconda
  - conda-forge
  - pytorch
  - bioconda


dependencies:
  - python>=3.7
  - pip
  - numpy>=1.19
  - scipy
  - pandas>=1.1.4
  - pyyaml
  - tqdm
  - sqlalchemy>=1.4
  - tiledb-py>=0.8.8
  - tiledb>=2.1
  - psycopg2
  - cyvcf2>=0.1.16
  - pyranges>=0.0.89
  - pyensembl
  - pysam
  - biopython
  - networkx>=2.5
  - scikit-learn>=0.23
  - plotnine
  - pyyaml
  - statsmodels
  - pytest
  - pytest-pep8
  - pip
  - pytorch>=1.6.0
  - tqdm
  - dask
  - jupyter
  - mlflow
  - papermill>=2.3.1
  - jinja2
  - snakemake
  
  - pip:
    # variantkey currently only exists on github
    - git+https://github.com/Genomicsplc/variantkey.git#egg=variantkey&subdirectory=python
 






